### PR TITLE
Added animation on scroll

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
I added animation on scroll to webpage please review my pull request

### CODE REVIEW

**Comment by Priyanshi662** [comment]
Looks great! @Sneha123-zudo please resolve the conflicts ,due to recent merge.

**Comment by Sneha123-zudo** [comment]
Done please have a look now

**Comment by Sneha123-zudo** [comment]
Resolved conflicts , please check it

**Comment by Priyanshi662** [comment]
@Sneha123-zudo  the layout of the cards is being changed. only single card appearing at one row. please resolve the issue.

**Pull request closed without merging**
