### PR TITLE
Addition of snake game completed (issue #51) 

### LINKED ISSUE #51: addition of snake game
@Priyanshi662 i would like to add the snake game. plz assign it to me under jwoc'24

### PR DESCRIPTION
**Pull request by vishal2005025**
# closes #51

### CODE REVIEW

**Comment by vishal2005025** [comment]
Mam, please review and merge this game..please...
Name : Vishal Malyan

**Comment by vishal2005025** [comment]
Mam , please merge.....

**Comment by Priyanshi662** [comment]
@vishal2005025  you cannot make PR without assignment, and that too already completed issue.

**Comment by vishal2005025** [comment]
Mam , after you assigning me I had created pr..
Please accept

**Pull request merged**
