### PR TITLE
main page css improved under issue #57

### PR DESCRIPTION
**Pull request by KhushiAgarwal22**
Screenshot 2024-01-23 223141

### CODE REVIEW

**Comment by KhushiAgarwal22** [comment]
Please view and accept my PR with regard to issue #57 
JWOC'24
@Priyanshi662

**Comment by Priyanshi662** [comment]
@KhushiAgarwal22  looks great! please resolve the conflicts.

**Comment by KhushiAgarwal22** [comment]
I have resolved the conflict. Kindly merge my PR now.
@Priyanshi662

**Comment by Priyanshi662** [comment]
@KhushiAgarwal22  please review again, there are still conflicts

**Comment by KhushiAgarwal22** [comment]
okay will look.

**Comment by KhushiAgarwal22** [comment]
resolved the conflicts. Please merge my PR now.
@Priyanshi662

**Pull request merged**
