### PR TITLE
Enhanced The UI of the Complete website And Made the website Completely Responsive.

### PR DESCRIPTION
**Pull request by SohanRC**
Enhanced the UI of the Complete website by creating a seperate Home Page and a Cards Section. Also added a few Animations to make the website attractive. The Website is completely responsive.

### CODE REVIEW

**Comment by SohanRC** [comment]
@Priyanshi662 I have submitted a PR Request. Kindly Review it.

**Comment by SohanRC** [comment]
@Priyanshi662 Kindly Review My Pull Request .

**Comment by Priyanshi662** [comment]
@SohanRC there are conflicts still

**Comment by SohanRC** [comment]
@Priyanshi662 I cannot understand what is the conflict. I have changed the code because of improving the UI ! Can't i do that ?

**Comment by SohanRC** [comment]
@Priyanshi662 Please tell me as it is my first time contributing to a Open source.

**Pull request closed without merging**
