### PR TITLE
Updated Footer Section

### PR DESCRIPTION
**Pull request by Aadhya-Sharma**
Transformed the website's footer with a synchronized color theme, refined text alignment, and added engaging hover effects to social media icons for a polished and interactive user experience.

Fixes issue #212 

Screenshot 2024-01-29 224921

### CODE REVIEW

**Comment by Priyanshi662** [comment]
due to merge of similar issue, conflicts have occurred, please resolve and make PR.

**Comment by Aadhya-Sharma** [comment]
@Priyanshi662  How to resolve the conflicts ? What steps do I need to follow ?

**Comment by Priyanshi662** [comment]
@Aadhya-Sharma  conflicts occur when the changes are overridden by another PR. you need to pull the changes in the command line and make the PR again.

**Comment by AftabMankapure** [comment]
@Aadhya-Sharma  just do simple steps 
just copy the new index file code form main repo 
and just update the footer section with your code

**Pull request closed without merging**
