### PR TITLE
Added a random color generator as a contribution under JWOC'24

### PR DESCRIPTION
**Pull request by SuvayuN**
I added a random color generator as a issue under #314 as a contribution under JWOC'24. It generates random color each time with a single click.

### CODE REVIEW

**Comment by Priyanshi662** [comment]
@SuvayuN  the colors are not being generated, its only showing the RGB values, please check.

**Comment by SuvayuN** [comment]
> @SuvayuN the colors are not being generated, its only showing the RGB values, please check.

The colors are being generated inside the div in my deploy preview

**Comment by Priyanshi662** [comment]
image

attaching screenshot, it is not showing the color

**Comment by SuvayuN** [comment]
> image
> 
> attaching screenshot, it is not showing the color

If you cross the deploy preview window(showing in the lower side of the screen)I guess it will work properly

**Comment by SuvayuN** [comment]
Screenshot 2024-02-15 202504
Mine is working after closing that

**Pull request merged**
