### PR TITLE
Go To Top button and progress bar added.

### LINKED ISSUE #175: Feature Request - Add "Go to Top" Button
The current website lacks a "Go to Top" button, which can enhance user experience by allowing them to quickly navigate back to the top of the page. This feature is especially useful for pages with lengthy content, ensuring users can easily return to the start without manual scrolling.

Proposed Changes
Implement a "Go to Top" button that appears as users scroll down the page.
Position the button in a corner of the screen, maintaining visibility but not obstructing content.
Ensure smooth scrolling animation when users click the button.

Benefits
Improved user navigation by providing a convenient way to return to the top.
Enhances overall user experience, particularly on pages with extensive content.
Demonstrates a commitment to user-friendly design practices.

image
**image is just an example.

### PR DESCRIPTION
**Pull request by rahat2134**
fix : #175 
*also add progress bar*
Screenshot 2024-01-28 at 4 40 58 PM
Screenshot 2024-01-28 at 4 41 11 PM

### CODE REVIEW

**Comment by rahat2134** [comment]
@Priyanshi662 PTAL and if possible then change the difficulty level to hard(see the PR).Thank You.

**Comment by Priyanshi662** [comment]
@rahat2134 please resolve conflicts

**Comment by rahat2134** [comment]
@Priyanshi662 i will update these conflict as soon as possible, Thank You.

**Comment by Priyanshi662** [comment]
@rahat2134  progress? , i'll be closing this PR, please make again whenever you're done.

**Pull request closed without merging**
