### PR TITLE
Add: Sidebar

### LINKED ISSUE #16: Add Responsive Nav bar (Sidebar for mobile devices)
Please allow me to work on it under jwoc tag!

### PR DESCRIPTION
**Pull request by AaadityaG**
Closes #16 

https://github.com/Priyanshi662/FunFusion/assets/114663382/357f2893-24f5-4e94-826d-c4d01b9e6ddc

## Please consider this with JWoC tag!

### CODE REVIEW

**Comment by Priyanshi662** [comment]
the sidebar is looking nice , but in desktop site the heading is not in the middle ,please fix and make pr again.
image

**Comment by AaadityaG** [comment]
Please add JWOC tag!

**Comment by Priyanshi662** [comment]
has conflicts, pull the changes and make PR @AaadityaG

**Comment by AaadityaG** [comment]
raising new pr

**Pull request closed without merging**
