### PR TITLE
#57 ADD BACKGROUND AND IMPROVE CSS OF FRONT PAGE

### PR DESCRIPTION
**Pull request by KhushiAgarwal22**
Pull Request with regard to issue #57 under JWOC 24

please look at the changes and accept @Priyanshi662 
Under JWOC 24

### CODE REVIEW

**Comment by KhushiAgarwal22** [comment]
Here is the screenshot of the changes made-

Screenshot 2024-01-21 140711

**Comment by Priyanshi662** [comment]
@KhushiAgarwal22  please improve the alignment of the cards.  Try to use flexbox or grid for styling the cards.

**Comment by KhushiAgarwal22** [comment]
I have used grid only ..could you please specify a little more what kind of alignment you are expecting so I could work accordingly.
@Priyanshi662

**Comment by KhushiAgarwal22** [comment]
here is a demo of front page-

https://github.com/Priyanshi662/FunFusion/assets/121626411/1c9aa238-dc9f-49ca-8312-1ca74a0ddaef

 please check  @Priyanshi662

**Comment by Priyanshi662** [comment]
image
the alignment for hangman game is not proper. also there is a thumbnail below the cards. please remove it.
image

**Comment by KhushiAgarwal22** [comment]
okay i'll look into it 
@Priyanshi662

**Pull request closed without merging**
