### PR TITLE
Added restart game button and added score board

### LINKED ISSUE #15: tic-tac-toe button and score
I want to add new match button to the tic-tac-toe game and would like to add the feature so it keeps track of the total number of wins , losses and ties .
Please assign me this issue under JWOC 2024.

### PR DESCRIPTION
**Pull request by madhurima316**
close #15

### CODE REVIEW

**Comment by Priyanshi662** [comment]
@madhurima316  please remove the merge conflicts

**Comment by madhurima316** [comment]
Can you please guide me how would I be able to resolve conflicts . I am not getting the option now.
t-t-t-github

**Comment by Priyanshi662** [comment]
@madhurima316  on the command line please pull the changes and then make another PR.

**Comment by madhurima316** [comment]
ma'am previously my code was running , but after pulling now my code isn't working ...maybe because tic-tac-toe game is under some subfolder which already uses the variables I have used...ma'am will you please check and help me. 
Maybe that's why previously conflict was arising.

**Comment by madhurima316** [comment]
May I know if my contribution is accepted or not

**Pull request closed without merging**
