### PR TITLE
stick hero game

### PR DESCRIPTION
**Pull request by ratnojitsaha**
simple game made using concepts of html css and javascript,

issue no - #254

JWOC 2024

screenshots - 
Screenshot (526)
Screenshot (527)

this screenshots shows the game starting and game over conditions.!!

PLEASE CONSIDER MY LATE SUBMISSION..

### CODE REVIEW

**Comment by Priyanshi662** [comment]
@ratnojitsaha , looks great!! please add the card for the game on the main site too

**Comment by ratnojitsaha** [comment]
@Priyanshi662 ok

**Comment by ratnojitsaha** [comment]
@Priyanshi662 idk what i did yesterday night it seems the changed i made yesterday made no sense, i am opening another pull req kindly check and merge, because the card is not showing in the main index page

**Comment by ratnojitsaha** [comment]
@Priyanshi662 i did some changes yesterday but were meaningless , please check this new pushed details

**Comment by ratnojitsaha** [comment]
the last pushed had some errors, please check newly pushed details.

**Pull request merged**
