### PR TITLE
Improve Sudoku Game

### PR DESCRIPTION
**Pull request by Surajit0573**
Issue : #355 
changes : 
- Added Difficulty options
- Added Lives for limit maximum wrong input 
- Fixed Overflow issue

image

### CODE REVIEW

**Comment by Priyanshi662** [comment]
@Surajit0573 can 4x4 be added as well?

**Comment by Surajit0573** [comment]
> @Surajit0573 can 4x4 be added as well?

as a different game ?

**Comment by Priyanshi662** [comment]
As sudoku is already present, if you can , please integrate it in this one only, there can be *types* button for the user to select 4x4 or 9 x 9 .

**Comment by Surajit0573** [comment]
> As sudoku is already present, if you can , please integrate it in this one only, there can be _types_ button for the user to select 4x4 or 9 x 9 .

Okey, I am working on it, can you please increase the difficulty tag !! I will try to add 6x6 also if possible.

**Comment by Surajit0573** [comment]
> As sudoku is already present, if you can , please integrate it in this one only, there can be _types_ button for the user to select 4x4 or 9 x 9 .

@Priyanshi662 , Sorry I could not do that. you can marge it as a improvement on 9x9 sudoku.

**Pull request merged**
