### PR TITLE
[ISSUE - 262] Adding a FAQ Page for the website

### LINKED ISSUE #262: Feature: Adding a FAQ Page for the website
## Description
I want to create a FAQ page that answers a variety of questions regarding the project.

## Reference of Template

image
image

## Checklist

- [x] I'll Follow the Contributing Guidelines
- [x] The FAQ Page will be Responsive

### PR DESCRIPTION
**Pull request by antilneeraj**
## Description

Added a comprehensive FAQ page to the project. I've ensured that the page is complete, responsive, and adheres to the project's theme.
- Also Fixed some Bugs with the NavBar to make its look and feel more comprehensive to the theme of the website.

## Related Issue

- Fixes #262

## Checklist

- [x] Responsive Design
- [x] Relevant FAQ Question
- [x] Themed Integration
- [x] Routing of FAQ Page
- [x] Feature Request

## Screenshots

I have attached screenshots of the FAQ page to provide a visual representation of the changes. Feel free to review and provide feedback.

image
image

## Additional Notes

I have thoroughly tested the functionality and appearance of the FAQ page to ensure a smooth user experience. If there are any specific areas that require attention or if you have additional feedback, please let me know.

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Priyanshi662 This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the `JWOC` and if possible, a `HARD` Difficulty label to this pull request as I have also fixed some alignment bugs that are there in the navbar.

waiting for your feedback...

**Comment by Priyanshi662** [comment]
@antilneeraj  looks impressive!! please resolve the conflicts and I'll merge the pr

**Comment by antilneeraj** [comment]
Alright!

**Comment by antilneeraj** [comment]
Hey @Priyanshi662, The merge conflicts are resolved please review the PR again and promptly provide your feedback.

**Pull request merged**
